import type { Garment } from '@/types/wardrobe';

/**
 * Armário de demonstração.
 *
 * Dezesseis peças, escolhidas para exercitar o produto e não para encher a
 * grade: neutros que combinam entre si, um casaco pesado e um leve para a
 * regra de clima, e duas peças de uniforme para provar que uniforme nunca
 * aparece em look casual.
 *
 * Sem `imageUri`: até a captura existir, cada peça se apresenta pelo glifo da
 * própria categoria.
 */
export const wardrobeSeed: Garment[] = [
  {
    id: 'g1',
    name: 'Camisa de algodão',
    category: 'camisa',
    color: { name: 'Preto', hex: '#0D0D0D' },
    material: 'Algodão',
    seasons: ['outono', 'inverno', 'primavera'],
    occasions: ['trabalho', 'noite', 'encontro'],
    isUniform: false,
  },
  {
    id: 'g2',
    name: 'Camisa de linho',
    category: 'camisa',
    color: { name: 'Areia', hex: '#E7E2DA' },
    material: 'Linho',
    seasons: ['primavera', 'verao'],
    occasions: ['casual', 'viagem', 'encontro'],
    isUniform: false,
  },
  {
    id: 'g3',
    name: 'Camiseta de malha',
    category: 'camiseta',
    color: { name: 'Areia', hex: '#E7E2DA' },
    material: 'Algodão pima',
    seasons: ['primavera', 'verao'],
    occasions: ['casual', 'viagem'],
    isUniform: false,
  },
  {
    id: 'g4',
    name: 'Camiseta lisa',
    category: 'camiseta',
    color: { name: 'Preto', hex: '#0D0D0D' },
    material: 'Algodão',
    seasons: ['primavera', 'verao', 'outono'],
    occasions: ['casual', 'noite', 'viagem'],
    isUniform: false,
  },
  {
    id: 'g5',
    name: 'Calça de alfaiataria',
    category: 'calca',
    color: { name: 'Areia', hex: '#E7E2DA' },
    material: 'Lã fria',
    seasons: ['outono', 'inverno', 'primavera'],
    occasions: ['trabalho', 'encontro', 'noite'],
    isUniform: false,
  },
  {
    id: 'g6',
    name: 'Calça reta',
    category: 'calca',
    color: { name: 'Preto', hex: '#0D0D0D' },
    material: 'Sarja',
    seasons: ['outono', 'inverno'],
    occasions: ['casual', 'noite', 'trabalho'],
    isUniform: false,
  },
  {
    id: 'g7',
    name: 'Calça de moletom',
    category: 'calca',
    color: { name: 'Grafite', hex: '#1A1A1A' },
    material: 'Moletom',
    seasons: ['outono', 'inverno'],
    occasions: ['casual'],
    isUniform: false,
  },
  {
    id: 'g8',
    name: 'Bermuda de sarja',
    category: 'bermuda',
    color: { name: 'Areia', hex: '#E7E2DA' },
    material: 'Sarja',
    seasons: ['verao', 'primavera'],
    occasions: ['casual', 'viagem'],
    isUniform: false,
  },
  {
    id: 'g9',
    name: 'Casaco de lã',
    category: 'casaco',
    color: { name: 'Grafite', hex: '#1A1A1A' },
    material: 'Lã',
    seasons: ['outono', 'inverno'],
    occasions: ['trabalho', 'noite', 'encontro'],
    isUniform: false,
  },
  {
    id: 'g10',
    name: 'Jaqueta leve',
    category: 'casaco',
    color: { name: 'Areia', hex: '#E7E2DA' },
    material: 'Algodão encerado',
    seasons: ['primavera', 'outono'],
    occasions: ['casual', 'viagem'],
    isUniform: false,
  },
  {
    id: 'g11',
    name: 'Tênis de couro',
    category: 'calcado',
    color: { name: 'Branco', hex: '#F7F5F2' },
    material: 'Couro',
    seasons: ['primavera', 'verao', 'outono'],
    occasions: ['casual', 'trabalho', 'encontro'],
    isUniform: false,
  },
  {
    id: 'g12',
    name: 'Bota de camurça',
    category: 'calcado',
    color: { name: 'Grafite', hex: '#1A1A1A' },
    material: 'Camurça',
    seasons: ['outono', 'inverno'],
    occasions: ['noite', 'encontro', 'trabalho'],
    isUniform: false,
  },
  {
    id: 'g13',
    name: 'Bolsa de couro',
    category: 'acessorio',
    color: { name: 'Grafite', hex: '#1A1A1A' },
    material: 'Couro',
    seasons: ['primavera', 'verao', 'outono', 'inverno'],
    occasions: ['trabalho', 'viagem'],
    isUniform: false,
  },
  {
    id: 'g14',
    name: 'Cinto de couro',
    category: 'acessorio',
    color: { name: 'Preto', hex: '#0D0D0D' },
    material: 'Couro',
    seasons: ['primavera', 'verao', 'outono', 'inverno'],
    occasions: ['trabalho', 'noite', 'encontro'],
    isUniform: false,
  },
  // Uniforme — nunca deve aparecer em look casual.
  {
    id: 'g15',
    name: 'Polo do trabalho',
    category: 'camiseta',
    color: { name: 'Grafite', hex: '#1A1A1A' },
    material: 'Piquê',
    seasons: ['primavera', 'verao', 'outono', 'inverno'],
    occasions: ['trabalho'],
    isUniform: true,
  },
  {
    id: 'g16',
    name: 'Calça do uniforme',
    category: 'calca',
    color: { name: 'Preto', hex: '#0D0D0D' },
    material: 'Poliéster',
    seasons: ['primavera', 'verao', 'outono', 'inverno'],
    occasions: ['trabalho'],
    isUniform: true,
  },
];
